FROM python:3.8-slim-buster

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["hypercorn", "app:download_manager_app", "--bind", "0.0.0.0:8000", "--reload"]
