name: "🚀 CI"
on:
  pull_request:
    branches:
      - main
jobs:
  release:
    name: 🚀 publish
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v2
      - name: 🟢 node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: assafushy/dg-api-gate
          tags: |
            type=raw,value=${{steps.package-version.outputs.current-version}}-{{base_ref}}-{{sha}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # assafushy/dg-content-control-generator:${{steps.package-version.outputs.current-version}}${{env.GITHUB_BASE_REF}}
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # ghcr.io/ assafushy/dg-content-control-generator:latest
      # ghcr.io/ assafushy/dg-content-control-generator:{{version}}

